menu:
    home: /
    archive: /archives/
    about: /about/

favicon: /favicon.ico
logo: /logo.png

# 分类
categories:
    javascript: /categories/javascript/
    小程序: /categories/program/
    踩坑记录: /categories/pit/

# 首页文章默认封面
thumbs: [https://qiniu.fancyrobot.com/FoluToOg8lb6E1wQnn3EDkVQPoW1,
        https://qiniu.fancyrobot.com/FncOIoiMms69rEawnLu-yeYEPAQ1,
        https://qiniu.fancyrobot.com/Fqnnf414TLxLiFfgKMyJf40BPWEr,
        https://qiniu.fancyrobot.com/FukOrbgjoOWoyDgzLES7VDqcKxye,
        https://qiniu.fancyrobot.com/Fgvrd5QsJz2H38yRu3Pey8qzwacq,
        https://qiniu.fancyrobot.com/FhKb51X3la46syzZpsTS5HTEe8aD,
        https://qiniu.fancyrobot.com/Fjp8AlZ-fk8iFiN4QKBiM6dxSkbF,
        https://qiniu.fancyrobot.com/FnuXrTrK_O9f3KbOLXdlImiu6pzW,
        https://qiniu.fancyrobot.com/Fm-mCKV9pmou66SSSrVg0-heY60n,
        https://qiniu.fancyrobot.com/FnZZlQUg6rMfAp7GyMUssTLs3OOG,
        https://qiniu.fancyrobot.com/FhIbF6KmIijodnsIxFVDbjaZ9uLQ]

# Comment
# disqus: pupa
# duoshuo: xwartz

# Analytics
# google-analytics:
#ga: UA-69822347-1
# baidu-analytics:
# ba: //hm.baidu.com/hm.js?b9e5254ddb0a9c4c4cd158df0d05a54c
# qq mta
#qq:
#    sid: 500303098
#    cid: 500303108
# growingio
#go: 90b580e047dd0007

# theme version
version: 1.0.3
# theme branch
branch: next
# theme font cdn url
font: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
# theme style cdn url
css: //faustun.github.io/lib/css/blog/main.css
search: //faustun.github.io/lib/css/blog/search.css